### ISSUE TITLE
Not working on iOS 13

### ISSUE THREAD

**Issue by HonQii** [exyte/FloatingButton#10] opened 2021-06-06 11:17 UTC
FloatingButton on iOS 13 can not show submenu buttons. May be affected by Spacer!

The code in the example app also doesn’t work

**Comment by f3dm76** [comment] 2021-10-11 06:08
Hey @HonQii, extremely sorry for super late response, I think you are using iOS 15 by now, but please do let me know if you have any more trouble with the library. Thank you for reaching out, have a great day!

**Comment by f3dm76** [comment] 2021-10-29 08:24
Closing this for now, do not hesitate to reach out again, if the problem persists

**Closed as completed by f3dm76** 2021-10-29 08:24 UTC

**Comment by ValS01** [comment] 2022-10-25 15:17
The problem is still active
When I try to use the library in iOS 13 it doesn't work, a shame I can't use it.
